services:
  meilisearch:
    image: "getmeili/meilisearch:v1.5"
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "1234"
    volumes:
      - "./tmp/meili_data:/temp/meili_data"
  redis:
    image: "redis:6.2-alpine"
    ports:
      - '6379:6379'
#    volumes:
#      - cache:/temp/redis_data