name: SSH deploy Master

on:
  push:
    branches: [ master ]

env:
  DIR: /home/stejs/lilu-cbs-api
  SERVICE_NAME: lilu-cbs-api

jobs:
  deploy:
    name: Deploy Master
    runs-on: ubuntu-latest
    steps:
      - name: executing remote commands
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 84.242.115.52
          username: root
          password: ${{ secrets.ROOT_PASSWORD }}
          port: 22
          envs: DIR,SERVICE_NAME
          script: |
            echo "$DIR"
            cd $DIR
            echo "git pull"
            sudo -u stejs git pull
            echo "install dependencies"
            bun install
            echo "restart $SERVICE_NAME"
            systemctl restart $SERVICE_NAME
            echo "done"
